version: "3.8"
services:
  zookeeper:
    container_name: "zookeeper-kafka-deck"
    image: "zookeeper"
    ports:
      - "2181:2181"
  kafka:
    container_name: "kafka-kafka-deck"
    image: "confluentinc/cp-kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
